before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
env:
  - WEBDRIVER_BROWSER="firefox"
#before_script:
#  - export NODE_PATH=./node_modules/buttercup/node_modules/:./node_modules/:$NODE_PATH
language: node_js
node_js:
  - "stable"
