sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
#before_install:
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
#before_script:
#  - export NODE_PATH=./node_modules/buttercup/node_modules/:./node_modules/:$NODE_PATH
script:
  - npm run test-ci
language: node_js
node_js:
  - "4.3"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c803777205006fc90eef
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
